### ISSUE TITLE
Failed to load extension

### ISSUE THREAD

**Issue by nikindreus** [87andrewh/CornerCullingSourceEngine#3]
[SM] Extension culling.ext.so failed to load: /lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found

Hosting: myarena.ru
OS: Centos 7

**Comment by 87andrewh** [comment]
Ah, I had not heard of Centos before. I will look into this after finishing Overpass and Vertigo.

**Comment by 87andrewh** [comment]
Hi, sorry for the delay. I have some time to look into this.

First, do you have access to all of the server's files? If you do, I assume you could update GLIBCXX.

Otherwise, I suggest compiling a version with a static link for libstdc++ as suggested in:
https://forums.alliedmods.net/archive/index.php/t-285307.html

Are you familiar with AMBuild? If not, I can try to compile for you. It may take a few cycles of communication if I'm not able to test on your servers.
